#!/bin/bash

name="game-server"
image="lherman/game-server"

docker build -t "$image" .
docker stop "$name" 2> /dev/null && docker rm "$name" 2> /dev/null
docker run --name "$name" --restart=always -d -p 8081:8081 -p 8080:8080 "$image"